### ISSUE TITLE
Could you just, tell whats that module commons used in it ..

### ISSUE THREAD

**Issue by annamalai0511** [gokulsarveshsk/Floating-trash-detection#3]
as far i read the documentation of commons module, i didnt find the functions like load_model etc you have used in your code line .. 
![Screenshot from 2023-03-24 21-09-13](https://user-images.githubusercontent.com/73933212/227572445-2defc59c-a791-4c1d-bcbc-245b5ec27d2c.png)

**Comment by gokulsarveshsk** [comment]
<img width="628" alt="Screenshot 2023-03-24 at 9 29 27 PM" src="https://user-images.githubusercontent.com/106106967/227578144-8f772183-044c-42d5-9bf9-61248c57d481.png">

Kindly change the directory for your model's path and as well as labels file.
If any other help issues let me know.

**Comment by annamalai0511** [comment]
yes, i have tried with the updated address of that model downloaded from
roboflow .. still no update ..
still the same issue .. I guess you didn't upload your submodule user
defined function file with the repo you have created.
